all: masterp watchdog obstacle target
	
masterp:
	gcc master_client.c -o build/masterp
watchdog:
	gcc WD_client.c -o build/watchdog
obstacle:
	gcc obstacle.c -o build/obstacle
target:
	gcc target.c -o build/target